import { useEffect, useMemo, useState } from 'react';
import browser from 'webextension-polyfill';
import { EmptyState, PanelHeader } from '../components/AppShell';
import { sendToActiveTab } from '../browser/api';
import { localDatabase } from '../storage/database';
import { copyText, createId, now, truncate } from '../shared/utils';
import type { ComponentFormat, PageAnalysis, PageAsset, SavedComponent, SelectedElement, UserScript } from '../types';

interface AdvancedPanelProps { selection: SelectedElement | null; reportError: (operation: string, message: string, detail?: string) => void; }

const formats: Array<{ id: ComponentFormat; label: string }> = [
  { id: 'html-css', label: 'HTML + CSS' }, { id: 'react-jsx', label: 'React JSX' }, { id: 'react-css', label: 'React + CSS' }, { id: 'tailwind', label: 'Tailwind (best effort)' }, { id: 'vue', label: 'Vue' }, { id: 'svelte', label: 'Svelte' },
];

export function ComponentExtractorPanel({ selection, reportError }: AdvancedPanelProps) {
  const [format, setFormat] = useState<ComponentFormat>('html-css'); const [saved, setSaved] = useState(false);
  if (!selection) return <section><PanelHeader eyebrow="BROWSER-VISIBLE COMPONENTS" title="Component Extractor" description="Create a reusable local component from the selected DOM and browser-readable styles. DevLens does not claim to extract unavailable server-side code." /><EmptyState title="Select a page element first." description="Use Web Inspector to capture a real element, then return here to generate a local component representation." /></section>;
  const output = convertComponent(selection, format);
  const save = async () => { const component: SavedComponent = { id: createId('component'), title: `${selection.tagName} component`, format, html: output.markup, css: output.styles, sourceUrl: selection.sourceUrl, selector: selection.selector, createdAt: now() }; await localDatabase.put('components', component); setSaved(true); };
  return <section><PanelHeader eyebrow="BROWSER-VISIBLE COMPONENTS" title="Component Extractor" description="DevLens removes obvious tracking attributes and keeps only browser-visible markup and readable style context. Visual fidelity can vary for frameworks, inherited CSS, assets, and cross-origin styles." actions={<><button className="secondary-button" type="button" onClick={() => void copyText(`${output.markup}\n\n${output.styles}`).catch((error) => reportError('clipboard', 'DevLens could not copy the component.', String(error)))}>Copy</button><button className="button" type="button" onClick={() => void save()}>Save component</button></>} />{saved && <section className="notice">Component saved locally. Export it from Settings & Privacy with your DevLens backup.</section>}<div className="split-layout"><section className="data-panel stack"><h2>Output format</h2>{formats.map((option) => <button type="button" key={option.id} className={format === option.id ? 'list-item active' : 'list-item'} onClick={() => setFormat(option.id)}><span>{option.label}<small>{option.id === 'tailwind' ? 'Converts only simple common properties.' : 'Local generated representation'}</small></span></button>)}<section className="notice warning">Assets remain references to the page resources exposed to the browser. Private, authenticated, DRM, or cross-origin resources are not bypassed.</section></section><section className="data-panel"><h2>{formats.find((item) => item.id === format)?.label}</h2><pre className="code-block">{output.markup}</pre><div className="section-heading"><h2>Styles</h2></div><pre className="code-block">{output.styles || 'No directly readable CSS rule was available; use Inspector computed styles as a reference.'}</pre></section></div></section>;
}

function convertComponent(selection: SelectedElement, format: ComponentFormat): { markup: string; styles: string } {
  const cleanHtml = selection.outerHTML.replace(/\s(?:data-(?:analytics|track|ga)[\w-]*|onclick|onload)=("[^"]*"|'[^']*')/gi, '').replace(/\s(id|class)=("(?:css-|sc-|jsx-)[^"]*"|'(?:css-|sc-|jsx-)[^']*')/gi, '');
  const css = selection.cssText || `${selection.selector} {\n${Object.entries(selection.computedStyles).filter(([key]) => ['display', 'color', 'background-color', 'font-family', 'font-size', 'font-weight', 'padding', 'margin', 'border', 'border-radius', 'box-shadow', 'width', 'height', 'flex', 'gap'].includes(key)).map(([key, value]) => `  ${key}: ${value};`).join('\n')}\n}`;
  const pascal = `${selection.tagName.replace(/(^|[-_])(\w)/g, (_match, _prefix, character) => character.toUpperCase())}Component`;
  if (format === 'html-css') return { markup: cleanHtml, styles: css };
  if (format === 'react-css') return { markup: `export function ${pascal}() {\n  return (\n    ${htmlToJsx(cleanHtml).split('\n').join('\n    ')}\n  );\n}`, styles: css };
  if (format === 'react-jsx') return { markup: `export function ${pascal}() {\n  return (\n    ${htmlToJsx(cleanHtml).split('\n').join('\n    ')}\n  );\n}`, styles: '// Move any needed styles into your component stylesheet or CSS module.' };
  if (format === 'vue') return { markup: `<template>\n  ${cleanHtml.split('\n').join('\n  ')}\n</template>`, styles: `<style scoped>\n${css}\n</style>` };
  if (format === 'svelte') return { markup: cleanHtml, styles: `<style>\n${css}\n</style>` };
  return { markup: htmlToTailwind(cleanHtml, selection.computedStyles), styles: '// Tailwind conversion is best effort. Verify responsive and inherited styles.' };
}

function htmlToJsx(html: string): string { return html.replace(/class=/g, 'className=').replace(/for=/g, 'htmlFor=').replace(/\sstyle="([^"]*)"/g, (_match, value: string) => ` style={{ { ${value.split(';').filter(Boolean).map((entry) => { const [property, raw] = entry.split(':'); return `${property?.trim().replace(/-([a-z])/g, (_whole, char) => char.toUpperCase())}: '${raw?.trim()}'`; }).join(', ')} } }}`); }
function htmlToTailwind(html: string, style: Record<string, string>): string { const tokens = [style.display === 'flex' && 'flex', style.display === 'grid' && 'grid', style['align-items'] === 'center' && 'items-center', style['justify-content'] === 'center' && 'justify-center', style['font-weight'] === '700' && 'font-bold', style['border-radius'] !== '0px' && 'rounded', style.padding !== '0px' && 'p-4', style.margin !== '0px' && 'm-2'].filter(Boolean).join(' '); return html.replace(/class=("[^"]*"|'[^']*')/, `class="${tokens}"`); }

export function AssetExplorerPanel({ reportError }: Pick<AdvancedPanelProps, 'reportError'>) {
  const [assets, setAssets] = useState<PageAsset[]>([]); const [loading, setLoading] = useState(false);
  const inspect = async () => { setLoading(true); const response = await sendToActiveTab<PageAsset[]>({ type: 'COLLECT_ASSETS' }); setLoading(false); if (!response.ok) { reportError(response.error.operation, response.error.message, response.error.detail); return; } setAssets(response.data); };
  return <section><PanelHeader eyebrow="EXPOSED PAGE RESOURCES" title="Asset Explorer" description="List public, browser-exposed images, inline SVGs, fonts, stylesheets, and scripts. DevLens does not bypass authentication, DRM, paywalls, or access controls." actions={<button type="button" className="button" onClick={() => void inspect()}>{loading ? 'Inspecting…' : 'Inspect assets'}</button>} />{!assets.length ? <EmptyState title="No assets listed yet." description="Inspect the active permitted webpage to list browser-visible resource references." /> : <section className="data-panel"><table className="table"><thead><tr><th>Type</th><th>Resource</th><th>Actions</th></tr></thead><tbody>{assets.map((asset) => <tr key={`${asset.type}:${asset.url}`}><td><span className="tag">{asset.type}</span></td><td><strong>{asset.label}</strong><br /><code>{truncate(asset.url, 115)}</code></td><td><div className="inline"><button type="button" className="secondary-button" onClick={() => void copyText(asset.url).catch((error) => reportError('clipboard', 'DevLens could not copy the asset URL.', String(error)))}>Copy URL</button>{asset.url.startsWith('http') && <button type="button" className="secondary-button" onClick={() => void browser.tabs.create({ url: asset.url })}>Open</button>}</div></td></tr>)}</tbody></table></section>}</section>;
}

export function AnalyzerPanel({ reportError }: Pick<AdvancedPanelProps, 'reportError'>) {
  const [analysis, setAnalysis] = useState<PageAnalysis | null>(null); const [loading, setLoading] = useState(false);
  const run = async () => { setLoading(true); const response = await sendToActiveTab<PageAnalysis>({ type: 'ANALYZE_PAGE' }); setLoading(false); if (!response.ok) { reportError(response.error.operation, response.error.message, response.error.detail); return; } setAnalysis(response.data); };
  return <section><PanelHeader eyebrow="BROWSER-SIDE OBSERVATIONS" title="Page Analyzer" description="Review framework signals, exposed assets, page structure, and basic accessibility checks. This is not a complete security or accessibility audit." actions={<button className="button" type="button" onClick={() => void run()}>{loading ? 'Analyzing…' : 'Analyze page'}</button>} />{!analysis ? <EmptyState title="Run an active-page analysis." description="The analyzer uses browser-visible document data only and reports practical limitations rather than attempting a bypass." /> : <div className="stack"><div className="three-column"><Metric label="DOM nodes" value={analysis.structure.domNodes} /><Metric label="Interactive" value={analysis.structure.interactive} /><Metric label="Assets" value={analysis.assets.length} /></div><div className="two-column"><section className="data-panel"><h2>Framework signals</h2><div className="inline">{analysis.frameworks.length ? analysis.frameworks.map((item) => <span className="tag success" key={item}>{item}</span>) : <p className="panel-description">No high-confidence framework signature was found.</p>}</div><div className="section-heading"><h2>Styling</h2></div><div className="inline">{analysis.styling.map((item) => <span className="tag" key={item}>{item}</span>)}</div><div className="section-heading"><h2>Structure</h2></div><dl className="kv-grid"><dt>Links</dt><dd>{analysis.structure.links}</dd><dt>Buttons</dt><dd>{analysis.structure.buttons}</dd><dt>Forms</dt><dd>{analysis.structure.forms}</dd><dt>Images</dt><dd>{analysis.structure.images}</dd></dl></section><section className="data-panel"><h2>Basic accessibility signals</h2>{analysis.accessibility.length ? <div className="list">{analysis.accessibility.map((issue, index) => <div className="list-item" key={`${issue.selector}-${index}`}><span><strong>{issue.message}</strong><small>{issue.selector}</small></span><span className={issue.severity === 'warning' ? 'tag warning' : 'tag'}>{issue.severity}</span></div>)}</div> : <section className="notice">No basic issues were found by this limited browser-side check. Manual auditing is still recommended.</section>}</section></div></div>}</section>;
}

function Metric({ label, value }: { label: string; value: number }) { return <section className="metric-card"><p className="metric-label">{label}</p><p className="metric-value">{value}</p></section>; }

export function ScriptLabPanel({ reportError }: Pick<AdvancedPanelProps, 'reportError'>) {
  const [scripts, setScripts] = useState<UserScript[]>([]); const [draft, setDraft] = useState<UserScript | null>(null); const [logs, setLogs] = useState<string[]>([]);
  const refresh = () => void localDatabase.list<UserScript>('scripts').then((items) => setScripts(items)).catch((error) => reportError('script-lab', 'DevLens could not read local scripts.', String(error)));
  useEffect(refresh, []);
  const persist = async (script: UserScript) => { await localDatabase.put('scripts', script); const next = [...scripts.filter((item) => item.id !== script.id), script]; await browser.storage.local.set({ scripts: next }); setScripts(next); setDraft(null); };
  const run = async (script: UserScript) => { const response = await sendToActiveTab<{ logs: string[] }>({ type: 'RUN_USER_SCRIPT', script }); if (!response.ok) { reportError(response.error.operation, response.error.message, response.error.detail); return; } setLogs(response.data.logs); };
  const toggle = async (script: UserScript) => { if (!script.enabled) { const granted = await browser.permissions.request({ permissions: ['tabs'] }); if (!granted) { reportError('script-lab', 'Automatic matching scripts need the optional Tabs permission to evaluate their own URL patterns.'); return; } } await persist({ ...script, enabled: !script.enabled, updatedAt: now() }); };
  return <section><PanelHeader eyebrow="ISOLATED EXTENSION WORLD" title="Script Lab" description="Run developer-authored JavaScript in DevLens’s isolated content-script world. Scripts cannot bypass browser security, access protected data, or automatically escape their granted site permissions." actions={<button className="button" type="button" onClick={() => setDraft({ id: createId('script'), name: 'Untitled script', description: '', matches: ['https://example.com/*'], code: 'devlens.log(devlens.selection);', enabled: false, createdAt: now(), updatedAt: now() })}>New script</button>} /><div className="split-layout"><section className="data-panel"><h2>Local scripts</h2><div className="list">{scripts.map((script) => <div className="list-item" key={script.id}><span><strong>{script.name}</strong><small>{script.matches.join(', ')}</small></span><div className="inline"><button type="button" className="secondary-button" onClick={() => void run(script)}>Run once</button><button type="button" className="secondary-button" onClick={() => setDraft(script)}>Edit</button><button className="toggle" type="button" aria-checked={script.enabled} aria-label={`${script.enabled ? 'Disable' : 'Enable'} ${script.name}`} onClick={() => void toggle(script)} /></div></div>)}</div>{!scripts.length && <EmptyState title="No scripts yet." description="Create a local script, review its URL matches, then run it explicitly on the active page." />}</section><section className="data-panel"><h2>Console output</h2><pre className="code-block">{logs.length ? logs.join('\n') : 'Run once writes devlens.log(...) output here.'}</pre><section className="notice warning">Auto-run requires an enabled script, a matching URL, and site access explicitly granted in Permission Center. DevLens does not silently expand permissions.</section></section></div>{draft && <ScriptEditor draft={draft} onClose={() => setDraft(null)} onSave={(next) => void persist(next)} onDelete={() => void localDatabase.delete('scripts', draft.id).then(refresh).then(() => setDraft(null))} />}</section>;
}

function ScriptEditor({ draft, onClose, onSave, onDelete }: { draft: UserScript; onClose: () => void; onSave: (script: UserScript) => void; onDelete: () => void }) {
  const [value, setValue] = useState(draft);
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="script-title"><div className="modal-header"><div><h2 id="script-title">Edit script</h2><p>Saved and executed only through DevLens.</p></div><button className="icon-button" type="button" onClick={onClose} aria-label="Close script editor">×</button></div><div className="stack"><div className="field"><label>Name</label><input value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></div><div className="field"><label>Description</label><input value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} /></div><div className="field"><label>URL match patterns, comma separated</label><input value={value.matches.join(', ')} onChange={(event) => setValue({ ...value, matches: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /></div><div className="field"><label>JavaScript</label><textarea rows={14} value={value.code} onChange={(event) => setValue({ ...value, code: event.target.value })} /></div></div><div className="inline space-between" style={{ marginTop: 15 }}><button className="danger-button" type="button" onClick={onDelete}>Delete</button><div className="inline"><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="button" type="button" onClick={() => onSave({ ...value, updatedAt: now() })}>Save script</button></div></div></section></div>;
}
