import { useEffect, useMemo, useState } from 'react';
import { EmptyState, PanelHeader } from '../components/AppShell';
import { getActiveTab } from '../browser/api';
import { localDatabase } from '../storage/database';
import { createId, now } from '../shared/utils';
import type { ResearchItem, ResearchSession, SavedComponent, Snippet } from '../types';

interface ResearchPanelProps { reportError: (operation: string, message: string, detail?: string) => void; }

export function ResearchPanel({ reportError }: ResearchPanelProps) {
  const [sessions, setSessions] = useState<ResearchSession[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [newTitle, setNewTitle] = useState(''); const [note, setNote] = useState(''); const [snippets, setSnippets] = useState<Snippet[]>([]); const [components, setComponents] = useState<SavedComponent[]>([]);
  const refresh = () => void Promise.all([localDatabase.list<ResearchSession>('researchSessions'), localDatabase.list<Snippet>('snippets'), localDatabase.list<SavedComponent>('components')]).then(([storedSessions, storedSnippets, storedComponents]) => { setSessions(storedSessions.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))); setSnippets(storedSnippets); setComponents(storedComponents); if (!selectedId && storedSessions[0]) setSelectedId(storedSessions[0].id); }).catch((error) => reportError('research', 'DevLens could not read local research sessions.', String(error)));
  useEffect(refresh, []);
  const selected = useMemo(() => sessions.find((session) => session.id === selectedId) ?? null, [sessions, selectedId]);
  const create = async () => { if (!newTitle.trim()) { reportError('research', 'A research session needs a project title.'); return; } const timestamp = now(); const session: ResearchSession = { id: createId('research'), title: newTitle.trim(), description: '', items: [], createdAt: timestamp, updatedAt: timestamp }; await localDatabase.put('researchSessions', session); setNewTitle(''); setSelectedId(session.id); refresh(); };
  const add = async (item: Omit<ResearchItem, 'id' | 'createdAt'>) => { if (!selected) return; const next = { ...selected, items: [...selected.items, { ...item, id: createId('item'), createdAt: now() }], updatedAt: now() }; await localDatabase.put('researchSessions', next); refresh(); };
  const addPage = async () => { const tab = await getActiveTab(); if (!tab?.url || !tab.title) { reportError('research', 'Open a normal webpage first to save it as a local reference.'); return; } await add({ type: 'webpage', title: tab.title, url: tab.url }); };
  const addNote = async () => { if (!note.trim()) return; await add({ type: 'note', title: 'Note', content: note.trim() }); setNote(''); };
  const remove = async (itemId: string) => { if (!selected) return; await localDatabase.put('researchSessions', { ...selected, items: selected.items.filter((item) => item.id !== itemId), updatedAt: now() }); refresh(); };
  return <section><PanelHeader eyebrow="LOCAL PROJECT CONTEXT" title="Research Sessions" description="Keep browser-visible references, notes, saved snippets, and extracted components together in local project folders. DevLens never uploads this research by default." /><div className="split-layout"><section className="data-panel stack"><h2>Projects</h2><div className="inline"><input aria-label="New research project title" placeholder="Portfolio website" value={newTitle} onChange={(event) => setNewTitle(event.target.value)} /><button className="button" type="button" onClick={() => void create()}>Create</button></div><div className="list">{sessions.map((session) => <button className={session.id === selected?.id ? 'list-item active' : 'list-item'} type="button" key={session.id} onClick={() => setSelectedId(session.id)}><span><strong>{session.title}</strong><small>{session.items.length} saved items</small></span></button>)}</div>{!sessions.length && <EmptyState title="Create a research session." description="Start with a project name, then save relevant webpages, snippets, components, and notes." />}</section>{selected ? <section className="data-panel stack"><div className="inline space-between"><div><h2>{selected.title}</h2><p className="panel-description">{selected.items.length} local items</p></div><button className="button" type="button" onClick={() => void addPage()}>Save current page</button></div><div className="form-grid"><div className="field wide"><label>Quick note</label><textarea rows={3} value={note} onChange={(event) => setNote(event.target.value)} /></div></div><div className="inline"><button className="secondary-button" type="button" onClick={() => void addNote()}>Save note</button>{snippets.slice(0, 3).map((snippet) => <button className="secondary-button" key={snippet.id} type="button" onClick={() => void add({ type: 'snippet', title: snippet.title, content: snippet.code })}>+ {snippet.title}</button>)}{components.slice(0, 3).map((component) => <button className="secondary-button" key={component.id} type="button" onClick={() => void add({ type: 'component', title: component.title, url: component.sourceUrl, content: component.html })}>+ {component.title}</button>)}</div><div className="list">{selected.items.map((item) => <div className="list-item" key={item.id}><span><span className="tag">{item.type}</span> <strong>{item.title}</strong><small>{item.url || item.content?.slice(0, 100) || 'Saved local item'}</small></span><button className="danger-button" type="button" onClick={() => void remove(item.id)}>Remove</button></div>)}</div>{!selected.items.length && <EmptyState title="Save sources to this session." description="Add the active webpage, a note, local snippets, or saved browser-visible components." />}</section> : <section className="data-panel"><EmptyState title="Select or create a project." description="Research sessions remain in this browser until you export a backup." /></section>}</div></section>;
}
